version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hiwiadmin
      POSTGRES_PASSWORD: hiwiadmin
      POSTGRES_DB: CASCBdatabase
    ports:
      - "5432:5432"
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hiwiadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: RubberDuck!007
    ports:
      - "5050:80"
    depends_on:
      - db


