version: '3.8'

services:
  cascb:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db # db container name, they have to match
      - DB_PORT=5432
      - DB_USER=hiwiadmin
      - DB_PASSWORD=hiwiadmin
      - DB_NAME=CASCBdatabase
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hiwiadmin
      POSTGRES_PASSWORD: hiwiadmin
      POSTGRES_DB: CASCBdatabase
  
  